"""
Patch OLP-OPS-001_Operations_Manual.docx:
- Remove emoji characters from all text
- Fix conda env name bde → olist
- Add Dagster orchestration content to section 4
"""
import re
from docx import Document
from docx.shared import Pt, RGBColor
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

EMOJI_RE = re.compile(
    "["
    "\U0001F000-\U0001FFFF"
    "\U00002600-\U000027BF"
    "\U0000FE0F"
    "\U000020D0-\U000020FF"
    "\U00002702-\U000027B0"
    "]+",
    flags=re.UNICODE,
)

# Additional common emojis as literal chars
SPECIFIC = ["📋", "📅", "🔖", "📦", "⚙️", "⚙", "✅", "❌", "⚠️"]


def strip_emoji(text):
    for e in SPECIFIC:
        text = text.replace(e, "")
    text = EMOJI_RE.sub("", text)
    return text


def clean_runs(para):
    for run in para.runs:
        if run.text:
            cleaned = strip_emoji(run.text)
            # Fix field labels: remove leftover whitespace before colon
            cleaned = re.sub(r'\s{2,}:', ':', cleaned)
            run.text = cleaned


def fix_env(para):
    for run in para.runs:
        if run.text:
            run.text = run.text.replace("bde-environment.yml", "olist-environment.yml")
            run.text = run.text.replace("conda activate bde", "conda activate olist")


NEW_STRUCTURE = (
    "olist_platform/                 <- PROJECT_ROOT (all paths resolve from here)\n"
    "|\n"
    "|-- .env.example               <- Template: copy to .env and fill in values\n"
    "|-- .env                       <- Your credentials (NEVER commit to Git)\n"
    "|-- .gitignore\n"
    "|-- requirements.txt           <- All Python dependencies (pinned versions)\n"
    "|-- olist-environment.yml      <- Conda environment definition\n"
    "|-- meltano.yml                <- Meltano config (tap-csv -> target-bigquery)\n"
    "|-- dagster.yaml               <- Dagster instance config (SQLite storage)\n"
    "|\n"
    "|-- data/raw/                  <- Place all 11 Olist CSV files here\n"
    "|\n"
    "|-- ingestion/\n"
    "|   |-- ingest_to_bigquery.py  <- Loads 10 core CSVs to BigQuery olist_raw\n"
    "|   `-- ingest_geolocation.py  <- Deduplicates 1M geo rows, loads DimGeography\n"
    "|\n"
    "|-- warehouse/schema.sql       <- Star schema DDL (dimensions + facts)\n"
    "|\n"
    "|-- dbt_project/               <- dbt transformation project\n"
    "|   |-- dbt_project.yml\n"
    "|   |-- profiles/profiles.yml  <- BigQuery connection (reads from .env)\n"
    "|   `-- models/\n"
    "|       |-- staging/           <- 9 staging views (raw -> clean)\n"
    "|       `-- marts/             <- 7 analytics mart tables\n"
    "|\n"
    "|-- data_quality/\n"
    "|   |-- dq_validation.py       <- 57+ pre-load checks on core datasets\n"
    "|   `-- dq_geolocation.py      <- 30 checks on geolocation data\n"
    "|\n"
    "|-- orchestration/\n"
    "|   |-- olist_pipeline_dag.py  <- Airflow DAG (legacy reference)\n"
    "|   `-- dagster/               <- Active Dagster orchestration (primary)\n"
    "|       |-- __init__.py        <- Definitions entry point\n"
    "|       |-- resources.py       <- DbtCliResource\n"
    "|       |-- jobs.py            <- 3 named jobs\n"
    "|       |-- schedules.py       <- Daily 06:00 UTC schedule\n"
    "|       `-- assets/            <- 9 pipeline assets\n"
    "|\n"
    "|-- notebooks/olist_analysis.py <- Analytics script -> 8 PNG charts\n"
    "|-- dashboard/index.html        <- Executive dashboard (open in browser)\n"
    "|-- reports/charts/             <- 8 PNG charts generated by analysis\n"
    "|-- docs/                       <- All documentation\n"
    "`-- logs/                       <- Pipeline run logs (auto-created)\n"
    "    |-- ingestion.log\n"
    "    |-- dq_results.csv\n"
    "    `-- dq_geolocation_report.json\n"
)

DAGSTER_CONTENT = (
    "Dagster is the primary orchestration engine. It provides an asset-based pipeline with "
    "a web UI, scheduled runs, and observability.\n\n"
    "Launch (development):\n"
    "    conda activate olist\n"
    "    cd olist_platform\n"
    "    DAGSTER_HOME=$(pwd) dagster dev -m orchestration.dagster\n"
    "    # Opens UI at http://localhost:3000\n\n"
    "Launch (production daemon):\n"
    "    DAGSTER_HOME=$(pwd) dagster-daemon run &\n"
    "    DAGSTER_HOME=$(pwd) dagster-webserver -m orchestration.dagster -p 3000 &\n\n"
    "Manual job trigger (CLI):\n"
    "    dagster job execute -m orchestration.dagster -j olist_daily_pipeline\n"
    "    dagster job execute -m orchestration.dagster -j olist_ingest_only\n"
    "    dagster job execute -m orchestration.dagster -j olist_dbt_only\n\n"
    "The schedule 'olist_daily_at_0600_utc' auto-starts when the daemon launches "
    "(default_status=RUNNING — no manual activation needed).\n\n"
    "Assets and groups:\n"
    "    [ingestion]     meltano_core_extract_load, meltano_geo_extract_load\n"
    "    [data_quality]  dq_core_validation, dq_geo_validation\n"
    "    [warehouse]     star_schema_build\n"
    "    [dbt]           dbt_staging, dbt_marts, dbt_tests\n"
    "    [analytics]     olist_analytics_charts\n"
)


def fix_doc():
    doc = Document("docs/OLP-OPS-001_Operations_Manual.docx")

    structure_replaced = False
    orchestration_found = False

    for para in doc.paragraphs:
        # Strip emojis from all paragraphs
        clean_runs(para)
        fix_env(para)

        txt = para.text.strip()

        # Replace the project structure block
        if not structure_replaced and "olist_platform/" in txt and ("PROJECT_ROOT" in txt or "project root" in txt.lower()):
            for run in para.runs:
                run.text = ""
            if para.runs:
                para.runs[0].text = NEW_STRUCTURE
                para.runs[0].font.name = "Courier New"
                para.runs[0].font.size = Pt(8)
            structure_replaced = True

        # Update the conda install section
        if "conda env create" in txt and "bde" in txt.lower():
            for run in para.runs:
                run.text = run.text.replace("bde-environment.yml", "olist-environment.yml")
                run.text = run.text.replace("conda activate bde", "conda activate olist")

        # Update Section 4 to add Dagster context
        if txt.startswith("4.") and "Running" in txt and "Application" in txt:
            orchestration_found = True

        if orchestration_found and not structure_replaced and "Every command below is run from" in txt:
            # Append Dagster information to this paragraph
            for run in para.runs:
                pass
            # Add a new run with Dagster content
            existing = para.text
            for run in para.runs:
                run.text = ""
            if para.runs:
                para.runs[0].text = (
                    existing.strip() + "\n\n"
                    "Orchestration (Dagster):\n"
                    "    DAGSTER_HOME=$(pwd) dagster dev -m orchestration.dagster\n"
                    "For full Dagster setup and launch options, see Section 3.5 below "
                    "and docs/dagster_orchestration.md."
                )

    # Also fix tables
    for tbl in doc.tables:
        for row in tbl.rows:
            for cell in row.cells:
                for para in cell.paragraphs:
                    clean_runs(para)
                    fix_env(para)

    # ── Find Section 4 and inject Dagster subsection ──────────────────────────
    # Strategy: find "Section 4" heading paragraph, then find the following
    # "Every command below" paragraph and insert Dagster block right after it.
    paras = doc.paragraphs
    insert_idx = None
    for i, para in enumerate(paras):
        if "Every command below is run from" in para.text:
            insert_idx = i
            break

    if insert_idx is not None:
        # We'll append a paragraph after the found paragraph
        ref_para = paras[insert_idx]
        ref_el = ref_para._element
        parent = ref_el.getparent()
        idx = list(parent).index(ref_el)

        # Create heading paragraph
        h_para = doc.add_paragraph()
        h_run = h_para.add_run("Pipeline Orchestration — Dagster")
        h_run.bold = True
        h_run.font.size = Pt(12)
        h_run.font.color.rgb = RGBColor(0x0D, 0x3B, 0x66)
        h_el = h_para._element
        parent.remove(h_el)
        parent.insert(idx + 1, h_el)

        # Create content paragraph
        d_para = doc.add_paragraph()
        d_run = d_para.add_run(DAGSTER_CONTENT)
        d_run.font.size = Pt(9.5)
        d_run.font.name = "Courier New"
        d_el = d_para._element
        parent.remove(d_el)
        parent.insert(idx + 2, d_el)

    doc.save("docs/OLP-OPS-001_Operations_Manual.docx")
    print("Saved docs/OLP-OPS-001_Operations_Manual.docx")


if __name__ == "__main__":
    fix_doc()
